### ISSUE TITLE
Faqs required on website

### ISSUE THREAD

**Issue by sukhbir-singh** [appteam-nith/HackOnHills#26]
@narendra36 @RamolaWeb @jaykay12 @atul-kumar02 @saurabh0402  
Add faqs on this issue as per needs.

List of faqs required to be added to website:-

1. Is this hackathon an online event or offline?
Ans. Hack on hills is offline event and as a participant you need to be present at NIT Hamirpur campus one or two day before the event at least.

2. Do this hackathon has any participation fees for students?
Ans. No. The hackathon is free of cost for any student from any college all over India.

3. What are all the restrictions on Team formations for the event?
* Any Team can have at most 5 members
* If a Team have participants from NIT Hamirpur or IIIT Una, then the team members are restricted to contain atmost 3 members from 3th Year, 4th Year or 5th Year. 

4. What should I do if I do not have any team yet?
Ans. Just fill out the form leaving team name as blank, and according to skills you have filled out we will match you with the best team possible during Pre-Hackathon meeting.

5. What are the Perks and Benefits of Participating in this Hackathon?
Ans. Hackathon Provide hands on experience with the experts from different field working on the Projects like Crypto Currency, AI, Machine Learning. This will help to give a head start if any one want to make project on the field. Along with that the participant will be provided with cool swags, stickers and refreshment and to keep them up. 

6. What are the Accommodation Facility for the Participant from Outside the College??
Ans- Participant will be provided with Accommodation and Food in the Guest House of College during the Hackathon Period.

**Comment by legendary-acp** [comment]
And also about about accommodation facility

**Comment by jaykay12** [comment]
@sukhbir-singh If No One is working on this issue right now, Assign this to me.
I will be working on the initial setup & add some important FAQs on which some more can be added later.
Or 
Rather, we should all post the main FAQ on this issue only & ask @saurabh0402 to design the FAQ section, so that later on all FAQ can be added to that.
I think later one is more apt, assign @saurabh0402 to this.

**Comment by sukhbir-singh** [comment]
Hi @legendary-acp we are happy to see you contributing to hack on hills. You can now add yourself as a contributor on the readme of this repo, just send a pull request with the additions.  

Also you are welcome to contibute to the websites code if your like and can open issues on this repo if you find any kind of bug or for discussing about anything corresponding to hack on hills. Please spread the word about "Hack On Hills" with your classmates and friends. 

Again, Thank you for participating in this discussion.

**Comment by the-codingninja** [comment]
I want to participate and while checking out the website I had those queries.

I want to ask another query- 

Is there any theme for the hackathon or is it free of ideas you can build on any idea?
@sukhbir-singh

**Comment by sukhbir-singh** [comment]
@ms10398  We have not decided any particular idea or theme yet for the hackathon but in case the hackathon is based on some idea or theme then also it will be disclosed at the start of hackathon only not before.
