### ISSUE TITLE
Need for a Zulip Chat

### ISSUE THREAD

**Issue by jaykay12** [appteam-nith/HackOnHills#27]
I think instead of using traditional Whatsapp Group method, we can use Zulip Chat as the major discussion room this time for our hack.
It will help in the various issues like:
* Important Announcements
* Team formations & handling participant's queries in more justified manner

I will prefer Zulip over all other similar alternatives like Slack, Gitter etc.

**Comment by sukhbir-singh** [comment]
We will target zulip as main chat sponsor next year. This time we are using Slack chat. 

Join the chat using following link: https://join.slack.com/t/hackonhills/shared_invite/enQtMzI0MDk0MDEyMzA4LTFiY2I0NTg2NTQ4N2FkMWZjNDA3YWY2MzcwZWNkZGQxZDVjZDgzYzFjZjZiM2U5NjQwODI3ZmM3Y2MxMDMwYmQ
