### ISSUE TITLE
Github link in the footer is directing to wrong link.

### ISSUE THREAD

**Issue by Jatin0312** [appteam-nith/HackOnHills#38]
The GitHub link should redirect to the https://github.com/appteam-nith/HackOnHills but instead it's redirecting to https://github.com/appteam-nith.
I would like to work on this issue.
Thanks :)

**Comment by sukhbir-singh** [comment]
Send pull request

**Comment by sukhbir-singh** [comment]
Thank you for the PR, feel free to add yourself as contributor in readme.md
Also while editing readme, please check out faqs checkbox.

**Comment by Jatin0312** [comment]
Ok sure :)
