### ISSUE TITLE
Registration Link not displaying properly in some devices like nexus 4 etc.

### ISSUE THREAD

**Issue by Jatin0312** [appteam-nith/HackOnHills#39]
**Here is the screenshot**

![bughackonhills](https://user-images.githubusercontent.com/17095817/37257045-85060860-2589-11e8-9e4e-6667f0eea22e.png)

I think it should be displayed on one line.

**Comment by sukhbir-singh** [comment]
Send pull request if interested in this issue

**Comment by Jatin0312** [comment]
I will try to correct it.

**Comment by zeus512** [comment]
is it fixed or still active?
